import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const fallbackModelsPath = process.env.OPENCODE_MODELS_FALLBACK_JSON

const modelsData = await (async () => {
  if (process.env.MODELS_DEV_API_JSON) return Bun.file(process.env.MODELS_DEV_API_JSON).text()

  try {
    return await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
  } catch (error) {
    if (!fallbackModelsPath) throw error
    console.warn(`Failed to fetch ${modelsUrl}/api.json, using fallback snapshot from ${fallbackModelsPath}`)
    return Bun.file(fallbackModelsPath).text()
  }
})()

await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")
