#!/usr/bin/env bash

# Get the latest Git tag
latest_tag=$(git tag --sort=committerdate | grep -E '^github-v[0-9]+\.[0-9]+\.[0-9]+$' | tail -1)
if [ -z "$latest_tag" ]; then
    echo "No github-v tags found, skipping publish"
    exit 0
fi
echo "Latest tag: $latest_tag"

# Update latest tag
git tag -d latest || true
git push origin :refs/tags/latest || true
git tag -a latest "$latest_tag" -m "Update latest to $latest_tag"
git push origin latest
